spring:
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/grupo-12-bbd-oo2-2021
=======
    url: jdbc:mysql://localhost:3306/grupo-12-bbd-oo2-2021?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
>>>>>>> estructura
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
<<<<<<< HEAD
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
=======
       ddl-auto: update
    properties:
       hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
>>>>>>> estructura
  thymeleaf:
    cache: false
